node ./generators/templates/test-azk-start.js   saitodisse    cloudtunes      azkfile > ./scripts/saitodisse-cloudtunes-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    dashboard       azkfile > ./scripts/saitodisse-dashboard-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    dillinger       azkfile > ./scripts/saitodisse-dillinger-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    discourse       azkfile > ./scripts/saitodisse-discourse-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    habitrpg        azkfile > ./scripts/saitodisse-habitrpg-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    huginn          azkfile > ./scripts/saitodisse-huginn-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    isomorphic500   azkfile > ./scripts/saitodisse-isomorphic500-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    lets-chat       azkfile > ./scripts/saitodisse-lets-chat-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    paperwork       azkfile > ./scripts/saitodisse-paperwork-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    platform        azkfile > ./scripts/saitodisse-platform-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    regexr          azkfile > ./scripts/saitodisse-regexr-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    shout           azkfile > ./scripts/saitodisse-shout-azkfile.sh
node ./generators/templates/test-azk-start.js   saitodisse    stringer        azkfile > ./scripts/saitodisse-stringer-azkfile.sh
